# Generated by Django 5.2.4 on 2025-07-25 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('proxy_type', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks5', 'SOCKS5')], default='http', max_length=10)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('geo', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='???', max_length=50)),
                ('days_idle', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('session_file', models.CharField(blank=True, max_length=200, null=True)),
                ('api_id', models.CharField(blank=True, max_length=32, null=True)),
                ('api_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('twofa_password', models.CharField(blank=True, max_length=128, null=True)),
                ('is_training', models.BooleanField(default=False)),
                ('training_status', models.CharField(blank=True, max_length=255, null=True)),
                ('invite_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_inviting', models.BooleanField(default=False)),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.proxy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntermediateChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_accounts', models.ManyToManyField(blank=True, related_name='intermediate_channels', to='accounts.telegramaccount')),
            ],
        ),
    ]
