# Generated by Django 5.2.4 on 2025-07-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='phone_code_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
