# Generated by Django 5.2.4 on 2025-10-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegramaccount_phone_code_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='daily_cap',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='sent_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='sent_today_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
