# Generated by Django 5.2.4 on 2025-10-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramaccount_cooldown_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='invite_refill_seconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='invite_success_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='invite_token_capacity',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='invite_token_refill_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='invite_tokens',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='send_refill_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='send_success_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='send_token_capacity',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='send_token_refill_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='send_tokens',
            field=models.IntegerField(default=1),
        ),
    ]
