# Generated by Django 5.2.4 on 2025-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_proxy_telegramaccount_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='proxy_type',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks5', 'SOCKS5')], default='http', max_length=10),
        ),
    ]
