# Generated by Django 5.2.4 on 2025-07-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_proxy_proxy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='api_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='api_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='twofa_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
