# Generated by Django 5.2.4 on 2025-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_telegramaccount_api_hash_telegramaccount_api_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='is_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='training_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
