# Generated by Django 5.2.4 on 2025-07-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_telegramaccount_is_training_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('added_accounts', models.ManyToManyField(blank=True, related_name='intermediate_channels', to='accounts.telegramaccount')),
            ],
        ),
    ]
