# Generated by Django 5.2.4 on 2025-07-23 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_intermediatechannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediatechannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
