# Generated by Django 5.2.4 on 2025-07-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_intermediatechannel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='invite_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
