# Generated by Django 5.2.4 on 2025-08-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardinggroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
