# Generated by Django 5.2.4 on 2025-08-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarding', '0002_forwardinggroup_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardingtask',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
