# Generated by Django 5.2.4 on 2025-07-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='message_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
